on:
  push:
    branches:
      - main
jobs:
  deploy-prod:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      #- name: Update composer
      #  run: php composer.phar update
      - name: Install npm
        run: npm install --production
      - name: Build vue app
        run: npm run build
#      - name: Deploy FE
#        uses: sand4rt/ftp-deployer@v1.8
#        with:
#          sftp: true
#          host: sftp.dedi137.your-server.de
#          port: 22
#          username: ${{ secrets.FTP_USER }}
#          password: ${{ secrets.FTP_PASS }}
#          remote_folder: /
#          local_folder: dist

      - name: Install screen npm
        working-directory: screen
        run: npm install --production
      - name: Build screen app
        working-directory: screen
        run: npm run build
      - name: Deploy Screen FE
        uses: sand4rt/ftp-deployer@v1.8
        with:
          sftp: true
          host: sftp.dedi137.your-server.de
          port: 22
          username: ${{ secrets.FTP_USER }}
          password: ${{ secrets.FTP_PASS }}
          remote_folder: /
          local_folder: screen/out

      - name: Deploy BE
        uses: sand4rt/ftp-deployer@v1.8
        with:
          sftp: true
          host: sftp.dedi137.your-server.de
          port: 22
          username: ${{ secrets.FTP_USER }}
          password: ${{ secrets.FTP_PASS }}
          remote_folder: /be/
          local_folder: be
