on: 
  push:
    branches:
      - main
jobs:
  deploy-prod:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      #- name: Update composer
      #  run: php composer.phar update
      - name: Install npm
        run: npm install
      - name: Build vue app
        run: npm run build
      - name: Deploy
        # You may pin to the exact commit or the version.
        # uses: sand4rt/ftp-deployer@518beaad91d1b18fd55a69321de7ed89080d2ae3
        uses: sand4rt/ftp-deployer@v1.8
        with:
          sftp: true
          host: sftp.dedi137.your-server.de
          port: 22
          username: ${{ secrets.FTP_USER }}
          password: ${{ secrets.FTP_PW }}
          remote_folder: /
          local_folder: dist
          #exclude:        
